In [83]:
import pandas as pd

In [84]:
df = pd.read_csv('data/cpsincomebyraceandhispanicorigin.csv',header=1,thousands=',',na_values='.')

df.rename(columns = {
    'Unnamed: 0':'Race',
    'Unnamed: 1':'Hispanic origin',
    'Unnamed: 2':'Totals',
    '$1 to $2,499\r\nor loss':'$1 to $2,499 or loss',
    '$100,000 and\r\nover': '$100,000 and over'
}, inplace = True)

df['Race'] = df['Race'].fillna(method='ffill')

df = df[~df['Totals'].isna()]

df['Hispanic origin'] = df['Hispanic origin'].replace({'Origin': 'Non Hispanic'})
df['Race'] = df['Race'].replace({'Race': 'White alone'})
df.loc[df['Hispanic origin'].isna(), ['Hispanic origin']] = 'Totals'

df

,Race,Hispanic origin,Totals,"$1 to $2,499 or loss",No Income,"$2,500 to $4,999","$5,000 to $7,499","$7,500 to $9,999","$10,000 to $12,499","$12,500 to $14,999",...,"$77,500 to $79,999","$80,000 to $82,499","$82,500 to $84,999","$85,000 to $87,499","$87,500 to $89,999","$90,000 to $92,499","$92,500 to $94,999","$95,000 to $97,499","$97,500 to $99,999","$100,000 and over"
0,Totals,Totals,320372.0,14260.0,91843.0,5984.0,7567.0,10151.0,12480.0,8386.0,...,1258.0,2893.0,1105.0,1698.0,895.0,2035.0,885.0,1304.0,788.0,22424.0
1,Totals,Non Hispanic,262702.0,12122.0,67821.0,4980.0,6076.0,8436.0,10180.0,7091.0,...,1170.0,2582.0,1020.0,1515.0,824.0,1858.0,817.0,1234.0,743.0,20907.0
3,Totals,Hispanic,57670.0,2139.0,24023.0,1004.0,1491.0,1715.0,2299.0,1295.0,...,88.0,311.0,84.0,183.0,71.0,177.0,68.0,70.0,45.0,1517.0
4,White alone,Totals,246310.0,11131.0,65668.0,4436.0,5603.0,7479.0,9435.0,6470.0,...,1041.0,2402.0,952.0,1395.0,755.0,1641.0,704.0,1099.0,655.0,18667.0
6,White alone,Non Hispanic,195453.0,9261.0,44621.0,3551.0,4286.0,5984.0,7403.0,5303.0,...,959.0,2138.0,874.0,1232.0,685.0,1486.0,647.0,1031.0,614.0,17318.0
8,White alone,Hispanic,50857.0,1870.0,21047.0,885.0,1317.0,1495.0,2032.0,1167.0,...,81.0,264.0,79.0,163.0,70.0,155.0,57.0,67.0,41.0,1348.0
9,Black or African American alone,Totals,42040.0,1513.0,14403.0,917.0,1228.0,1723.0,1929.0,1253.0,...,121.0,222.0,75.0,121.0,78.0,173.0,95.0,86.0,70.0,1283.0
10,Black or African American alone,Non Hispanic,39257.0,1396.0,13280.0,872.0,1140.0,1628.0,1805.0,1205.0,...,120.0,201.0,73.0,121.0,77.0,164.0,87.0,86.0,66.0,1218.0
12,Black or African American alone,Hispanic,2783.0,117.0,1122.0,45.0,89.0,95.0,123.0,48.0,...,0.0,21.0,2.0,NaN,0.0,9.0,8.0,NaN,4.0,65.0
13,American Indian and Alaska Native alone,Totals,3718.0,170.0,1362.0,92.0,122.0,153.0,148.0,88.0,...,10.0,17.0,5.0,11.0,5.0,11.0,4.0,2.0,2.0,120.0
14,American Indian and Alaska Native alone,Non Hispanic,2390.0,117.0,821.0,75.0,78.0,110.0,120.0,65.0,...,7.0,7.0,2.0,5.0,5.0,9.0,4.0,0.0,2.0,82.0
16,American Indian and Alaska Native alone,Hispanic,1327.0,54.0,541.0,18.0,44.0,43.0,29.0,23.0,...,3.0,10.0,2.0,6.0,NaN,3.0,NaN,2.0,NaN,38.0
17,Asian alone,Totals,18897.0,1012.0,5841.0,341.0,443.0,523.0,680.0,388.0,...,67.0,183.0,59.0,135.0,39.0,192.0,64.0,102.0,56.0,2048.0
18,Asian alone,Non Hispanic,18364.0,1000.0,5626.0,330.0,438.0,516.0,643.0,366.0,...,66.0,178.0,59.0,128.0,39.0,188.0,64.0,102.0,56.0,2035.0
20,Asian alone,Hispanic,532.0,13.0,215.0,11.0,4.0,7.0,37.0,22.0,...,0.0,4.0,NaN,7.0,NaN,4.0,NaN,NaN,NaN,12.0
21,Native Hawaiian and Other Pacific Islander alone,Totals,1289.0,74.0,484.0,18.0,29.0,36.0,59.0,33.0,...,2.0,15.0,3.0,0.0,3.0,1.0,1.0,1.0,1.0,71.0
22,Native Hawaiian and Other Pacific Islander alone,Non Hispanic,1043.0,62.0,373.0,14.0,26.0,24.0,50.0,26.0,...,2.0,15.0,3.0,0.0,3.0,1.0,1.0,1.0,1.0,62.0
24,Native Hawaiian and Other Pacific Islander alone,Hispanic,246.0,12.0,111.0,4.0,3.0,12.0,9.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
25,Two or more races,Totals,8119.0,359.0,4086.0,179.0,142.0,236.0,228.0,155.0,...,18.0,54.0,10.0,36.0,15.0,16.0,18.0,15.0,4.0,236.0
26,Two or more races,Non Hispanic,6194.0,287.0,3101.0,138.0,109.0,175.0,159.0,126.0,...,15.0,42.0,9.0,29.0,14.0,11.0,15.0,13.0,4.0,191.0
28,Two or more races,Hispanic,1925.0,72.0,985.0,41.0,34.0,62.0,69.0,29.0,...,3.0,11.0,0.0,7.0,1.0,6.0,3.0,1.0,NaN,44.0

In [101]:
brackets = {}

brackets['No Income'] = [
    'No Income'
]
brackets['Less than $10,000'] = [
    '$1 to $2,499 or loss',
    '$2,500 to $4,999',
    '$5,000 to $7,499',
    '$7,500 to $9,999'
]
brackets['$10,000 to $20,000'] = [
    '$10,000 to $12,499',
    '$12,500 to $14,999',
    '$15,000 to $17,499',
    '$17,500 to $19,999'
]
brackets['$20,000 to $30,000'] = [
    '$20,000 to $22,499',
    '$22,500 to $24,999',
    '$25,000 to $27,499',
    '$27,500 to $29,999'
]
brackets['$30,000 to $40,000'] = [
    '$30,000 to $32,499',
    '$32,500 to $34,999',
    '$35,000 to $37,499',
    '$37,500 to $39,999'
]
brackets['$40,000 to $50,000'] = [
    '$40,000 to $42,499',
    '$42,500 to $44,999',
    '$45,000 to $47,499',
    '$47,500 to $49,999'
]
brackets['$50,000 to $75,000'] = [
    '$50,000 to $52,499',
    '$52,500 to $54,999',
    '$55,000 to $57,499',
    '$57,500 to $59,999',
    '$60,000 to $62,499',
    '$62,500 to $64,999',
    '$65,000 to $67,499',
    '$67,500 to $69,999',
    '$70,000 to $72,499',
    '$72,500 to $74,999'
]
brackets['$75,000 to $100,000'] = [
    '$75,000 to $77,499',
    '$77,500 to $79,999',
    '$80,000 to $82,499',
    '$82,500 to $84,999',
    '$85,000 to $87,499',
    '$87,500 to $89,999',
    '$90,000 to $92,499',
    '$92,500 to $94,999',
    '$95,000 to $97,499',
    '$97,500 to $99,999'
]
brackets['$100,000 and over'] = [
    '$100,000 and over'
]

for bracket, cols in brackets.items():
    df[bracket] = df[cols].sum(axis=1)
    df[bracket + ' pct'] = df[bracket]/df['Totals']

pcts = df[['Race','Hispanic origin'] + [bracket + ' pct' for bracket in brackets.keys()]]

pcts

,Race,Hispanic origin,No Income pct,"Less than $10,000 pct","$10,000 to $20,000 pct","$20,000 to $30,000 pct","$30,000 to $40,000 pct","$40,000 to $50,000 pct","$50,000 to $75,000 pct","$75,000 to $100,000 pct","$100,000 and over pct"
0,Totals,Totals,0.286676,0.118494,0.122739,0.100830,0.084499,0.065034,0.102262,0.049467,0.069994
1,Totals,Non Hispanic,0.258167,0.120342,0.123002,0.100174,0.085093,0.068050,0.110467,0.055104,0.079584
3,Totals,Hispanic,0.416560,0.110092,0.121536,0.103780,0.081793,0.051274,0.064886,0.023773,0.026305
4,White alone,Totals,0.266607,0.116313,0.123158,0.102992,0.086099,0.068385,0.107815,0.052848,0.075787
6,White alone,Non Hispanic,0.228295,0.118095,0.123339,0.102326,0.087279,0.072800,0.118929,0.060352,0.088604
8,White alone,Hispanic,0.413847,0.109464,0.122461,0.105551,0.081562,0.051419,0.065104,0.023989,0.026506
9,Black or African American alone,Totals,0.342602,0.127997,0.137108,0.103925,0.086679,0.057136,0.082755,0.031327,0.030519
10,Black or African American alone,Non Hispanic,0.338284,0.128283,0.138141,0.103447,0.086354,0.057595,0.084647,0.032198,0.031026
12,Black or African American alone,Hispanic,0.403162,0.124326,0.121452,0.110672,0.091268,0.050665,0.055695,0.018326,0.023356
13,American Indian and Alaska Native alone,Totals,0.366326,0.144432,0.126412,0.091716,0.083378,0.057827,0.073964,0.022593,0.032275
14,American Indian and Alaska Native alone,Non Hispanic,0.343515,0.158996,0.133054,0.101674,0.067782,0.061925,0.077406,0.022594,0.034310
16,American Indian and Alaska Native alone,Hispanic,0.407687,0.119819,0.116051,0.073851,0.111530,0.052751,0.068576,0.022607,0.028636
17,Asian alone,Totals,0.309097,0.122718,0.097158,0.078425,0.071334,0.052495,0.098164,0.062179,0.108377
18,Asian alone,Non Hispanic,0.306360,0.124374,0.095676,0.077706,0.071008,0.052603,0.099161,0.062296,0.110815
20,Asian alone,Hispanic,0.404135,0.065789,0.148496,0.103383,0.082707,0.048872,0.062030,0.054511,0.022556
21,Native Hawaiian and Other Pacific Islander alone,Totals,0.375485,0.121800,0.114042,0.099302,0.072925,0.063615,0.068270,0.027153,0.055081
22,Native Hawaiian and Other Pacific Islander alone,Non Hispanic,0.357622,0.120805,0.116970,0.100671,0.078619,0.058485,0.075743,0.030681,0.059444
24,Native Hawaiian and Other Pacific Islander alone,Hispanic,0.451220,0.126016,0.101626,0.093496,0.048780,0.089431,0.040650,0.012195,0.040650
25,Two or more races,Totals,0.503264,0.112822,0.094839,0.075625,0.057889,0.036581,0.062816,0.027097,0.029068
26,Two or more races,Non Hispanic,0.500646,0.114466,0.094608,0.077494,0.058282,0.034388,0.059412,0.029706,0.030836
28,Two or more races,Hispanic,0.511688,0.108571,0.095584,0.069091,0.057143,0.043636,0.073247,0.017662,0.022857

In [100]:
pcts.sum(axis=1)

0     0.999994
1     0.999985
3     1.000000
4     1.000004
6     1.000020
8     0.999902
9     1.000048
10    0.999975
12    0.998922
13    0.998924
14    1.001255
16    1.001507
17    0.999947
18    1.000000
20    0.992481
21    0.997673
22    0.999041
24    1.004065
25    1.000000
26    0.999839
28    0.999481
dtype: float64

In [104]:
pcts[(pcts['Hispanic origin'] == 'Non Hispanic') | (pcts['Race'] == 'Totals')]

,Race,Hispanic origin,No Income pct,"Less than $10,000 pct","$10,000 to $20,000 pct","$20,000 to $30,000 pct","$30,000 to $40,000 pct","$40,000 to $50,000 pct","$50,000 to $75,000 pct","$75,000 to $100,000 pct","$100,000 and over pct"
0,Totals,Totals,0.286676,0.118494,0.122739,0.100830,0.084499,0.065034,0.102262,0.049467,0.069994
1,Totals,Non Hispanic,0.258167,0.120342,0.123002,0.100174,0.085093,0.068050,0.110467,0.055104,0.079584
3,Totals,Hispanic,0.416560,0.110092,0.121536,0.103780,0.081793,0.051274,0.064886,0.023773,0.026305
6,White alone,Non Hispanic,0.228295,0.118095,0.123339,0.102326,0.087279,0.072800,0.118929,0.060352,0.088604
10,Black or African American alone,Non Hispanic,0.338284,0.128283,0.138141,0.103447,0.086354,0.057595,0.084647,0.032198,0.031026
14,American Indian and Alaska Native alone,Non Hispanic,0.343515,0.158996,0.133054,0.101674,0.067782,0.061925,0.077406,0.022594,0.034310
18,Asian alone,Non Hispanic,0.306360,0.124374,0.095676,0.077706,0.071008,0.052603,0.099161,0.062296,0.110815
22,Native Hawaiian and Other Pacific Islander alone,Non Hispanic,0.357622,0.120805,0.116970,0.100671,0.078619,0.058485,0.075743,0.030681,0.059444
26,Two or more races,Non Hispanic,0.500646,0.114466,0.094608,0.077494,0.058282,0.034388,0.059412,0.029706,0.030836

In [105]:
pcts[(pcts['Hispanic origin'] == 'Non Hispanic') | (pcts['Race'] == 'Totals')].to_csv('assets/cpsincomebyraceandhispanicorigin.csv')