In [128]:
import pandas as pd

In [129]:
df = pd.read_csv('data/cpsincomebyraceandhispanicorigin.csv',header=1,thousands=',',na_values='.')

df.rename(columns = {
    'Unnamed: 0':'Race',
    'Unnamed: 1':'Hispanic origin',
    'Unnamed: 2':'Totals',
    '$1 to $2,499\r\nor loss':'$1 to $2,499 or loss',
    '$100,000 and\r\nover': '$100,000 and over'
}, inplace = True)

df['Race'] = df['Race'].fillna(method='ffill')

df = df[~df['Totals'].isna()]

df['Hispanic origin'] = df['Hispanic origin'].replace({'Origin': 'Non Hispanic'})
df['Race'] = df['Race'].replace({'Race': 'White alone'})
df.loc[df['Hispanic origin'].isna(), ['Hispanic origin']] = 'Totals'

df

,Race,Hispanic origin,Totals,"$1 to $2,499 or loss",No Income,"$2,500 to $4,999","$5,000 to $7,499","$7,500 to $9,999","$10,000 to $12,499","$12,500 to $14,999",...,"$77,500 to $79,999","$80,000 to $82,499","$82,500 to $84,999","$85,000 to $87,499","$87,500 to $89,999","$90,000 to $92,499","$92,500 to $94,999","$95,000 to $97,499","$97,500 to $99,999","$100,000 and over"
0,Totals,Totals,320372.000,14260.000,91843.000,5984.000,7567.000,10151.000,12480.000,8386.000,...,1258.000,2893.000,1105.000,1698.000,895.000,2035.000,885.000,1304.000,788.000,22424.000
1,Totals,Non Hispanic,262702.000,12122.000,67821.000,4980.000,6076.000,8436.000,10180.000,7091.000,...,1170.000,2582.000,1020.000,1515.000,824.000,1858.000,817.000,1234.000,743.000,20907.000
3,Totals,Hispanic,57670.000,2139.000,24023.000,1004.000,1491.000,1715.000,2299.000,1295.000,...,88.000,311.000,84.000,183.000,71.000,177.000,68.000,70.000,45.000,1517.000
4,White alone,Totals,246310.000,11131.000,65668.000,4436.000,5603.000,7479.000,9435.000,6470.000,...,1041.000,2402.000,952.000,1395.000,755.000,1641.000,704.000,1099.000,655.000,18667.000
6,White alone,Non Hispanic,195453.000,9261.000,44621.000,3551.000,4286.000,5984.000,7403.000,5303.000,...,959.000,2138.000,874.000,1232.000,685.000,1486.000,647.000,1031.000,614.000,17318.000
8,White alone,Hispanic,50857.000,1870.000,21047.000,885.000,1317.000,1495.000,2032.000,1167.000,...,81.000,264.000,79.000,163.000,70.000,155.000,57.000,67.000,41.000,1348.000
9,Black or African American alone,Totals,42040.000,1513.000,14403.000,917.000,1228.000,1723.000,1929.000,1253.000,...,121.000,222.000,75.000,121.000,78.000,173.000,95.000,86.000,70.000,1283.000
10,Black or African American alone,Non Hispanic,39257.000,1396.000,13280.000,872.000,1140.000,1628.000,1805.000,1205.000,...,120.000,201.000,73.000,121.000,77.000,164.000,87.000,86.000,66.000,1218.000
12,Black or African American alone,Hispanic,2783.000,117.000,1122.000,45.000,89.000,95.000,123.000,48.000,...,0.000,21.000,2.000,nan,0.000,9.000,8.000,nan,4.000,65.000
13,American Indian and Alaska Native alone,Totals,3718.000,170.000,1362.000,92.000,122.000,153.000,148.000,88.000,...,10.000,17.000,5.000,11.000,5.000,11.000,4.000,2.000,2.000,120.000
14,American Indian and Alaska Native alone,Non Hispanic,2390.000,117.000,821.000,75.000,78.000,110.000,120.000,65.000,...,7.000,7.000,2.000,5.000,5.000,9.000,4.000,0.000,2.000,82.000
16,American Indian and Alaska Native alone,Hispanic,1327.000,54.000,541.000,18.000,44.000,43.000,29.000,23.000,...,3.000,10.000,2.000,6.000,nan,3.000,nan,2.000,nan,38.000
17,Asian alone,Totals,18897.000,1012.000,5841.000,341.000,443.000,523.000,680.000,388.000,...,67.000,183.000,59.000,135.000,39.000,192.000,64.000,102.000,56.000,2048.000
18,Asian alone,Non Hispanic,18364.000,1000.000,5626.000,330.000,438.000,516.000,643.000,366.000,...,66.000,178.000,59.000,128.000,39.000,188.000,64.000,102.000,56.000,2035.000
20,Asian alone,Hispanic,532.000,13.000,215.000,11.000,4.000,7.000,37.000,22.000,...,0.000,4.000,nan,7.000,nan,4.000,nan,nan,nan,12.000
21,Native Hawaiian and Other Pacific Islander alone,Totals,1289.000,74.000,484.000,18.000,29.000,36.000,59.000,33.000,...,2.000,15.000,3.000,0.000,3.000,1.000,1.000,1.000,1.000,71.000
22,Native Hawaiian and Other Pacific Islander alone,Non Hispanic,1043.000,62.000,373.000,14.000,26.000,24.000,50.000,26.000,...,2.000,15.000,3.000,0.000,3.000,1.000,1.000,1.000,1.000,62.000
24,Native Hawaiian and Other Pacific Islander alone,Hispanic,246.000,12.000,111.000,4.000,3.000,12.000,9.000,6.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,10.000
25,Two or more races,Totals,8119.000,359.000,4086.000,179.000,142.000,236.000,228.000,155.000,...,18.000,54.000,10.000,36.000,15.000,16.000,18.000,15.000,4.000,236.000
26,Two or more races,Non Hispanic,6194.000,287.000,3101.000,138.000,109.000,175.000,159.000,126.000,...,15.000,42.000,9.000,29.000,14.000,11.000,15.000,13.000,4.000,191.000
28,Two or more races,Hispanic,1925.000,72.000,985.000,41.000,34.000,62.000,69.000,29.000,...,3.000,11.000,0.000,7.000,1.000,6.000,3.000,1.000,nan,44.000

In [130]:
brackets = {}

brackets['No Income'] = [
    'No Income'
]
brackets['Less than $10,000'] = [
    '$1 to $2,499 or loss',
    '$2,500 to $4,999',
    '$5,000 to $7,499',
    '$7,500 to $9,999'
]
brackets['$10,000 to $20,000'] = [
    '$10,000 to $12,499',
    '$12,500 to $14,999',
    '$15,000 to $17,499',
    '$17,500 to $19,999'
]
brackets['$20,000 to $30,000'] = [
    '$20,000 to $22,499',
    '$22,500 to $24,999',
    '$25,000 to $27,499',
    '$27,500 to $29,999'
]
brackets['$30,000 to $40,000'] = [
    '$30,000 to $32,499',
    '$32,500 to $34,999',
    '$35,000 to $37,499',
    '$37,500 to $39,999'
]
brackets['$40,000 to $50,000'] = [
    '$40,000 to $42,499',
    '$42,500 to $44,999',
    '$45,000 to $47,499',
    '$47,500 to $49,999'
]
brackets['$50,000 to $75,000'] = [
    '$50,000 to $52,499',
    '$52,500 to $54,999',
    '$55,000 to $57,499',
    '$57,500 to $59,999',
    '$60,000 to $62,499',
    '$62,500 to $64,999',
    '$65,000 to $67,499',
    '$67,500 to $69,999',
    '$70,000 to $72,499',
    '$72,500 to $74,999'
]
brackets['$75,000 to $100,000'] = [
    '$75,000 to $77,499',
    '$77,500 to $79,999',
    '$80,000 to $82,499',
    '$82,500 to $84,999',
    '$85,000 to $87,499',
    '$87,500 to $89,999',
    '$90,000 to $92,499',
    '$92,500 to $94,999',
    '$95,000 to $97,499',
    '$97,500 to $99,999'
]
brackets['$100,000 and over'] = [
    '$100,000 and over'
]

for bracket, cols in brackets.items():
    df[bracket] = df[cols].sum(axis=1)
    df[bracket + ' pct'] = df[bracket]/df['Totals']

pcts = df[['Race','Hispanic origin'] + [bracket + ' pct' for bracket in brackets.keys()]]

pcts

,Race,Hispanic origin,No Income pct,"Less than $10,000 pct","$10,000 to $20,000 pct","$20,000 to $30,000 pct","$30,000 to $40,000 pct","$40,000 to $50,000 pct","$50,000 to $75,000 pct","$75,000 to $100,000 pct","$100,000 and over pct"
0,Totals,Totals,0.287,0.118,0.123,0.101,0.084,0.065,0.102,0.049,0.070
1,Totals,Non Hispanic,0.258,0.120,0.123,0.100,0.085,0.068,0.110,0.055,0.080
3,Totals,Hispanic,0.417,0.110,0.122,0.104,0.082,0.051,0.065,0.024,0.026
4,White alone,Totals,0.267,0.116,0.123,0.103,0.086,0.068,0.108,0.053,0.076
6,White alone,Non Hispanic,0.228,0.118,0.123,0.102,0.087,0.073,0.119,0.060,0.089
8,White alone,Hispanic,0.414,0.109,0.122,0.106,0.082,0.051,0.065,0.024,0.027
9,Black or African American alone,Totals,0.343,0.128,0.137,0.104,0.087,0.057,0.083,0.031,0.031
10,Black or African American alone,Non Hispanic,0.338,0.128,0.138,0.103,0.086,0.058,0.085,0.032,0.031
12,Black or African American alone,Hispanic,0.403,0.124,0.121,0.111,0.091,0.051,0.056,0.018,0.023
13,American Indian and Alaska Native alone,Totals,0.366,0.144,0.126,0.092,0.083,0.058,0.074,0.023,0.032
14,American Indian and Alaska Native alone,Non Hispanic,0.344,0.159,0.133,0.102,0.068,0.062,0.077,0.023,0.034
16,American Indian and Alaska Native alone,Hispanic,0.408,0.120,0.116,0.074,0.112,0.053,0.069,0.023,0.029
17,Asian alone,Totals,0.309,0.123,0.097,0.078,0.071,0.052,0.098,0.062,0.108
18,Asian alone,Non Hispanic,0.306,0.124,0.096,0.078,0.071,0.053,0.099,0.062,0.111
20,Asian alone,Hispanic,0.404,0.066,0.148,0.103,0.083,0.049,0.062,0.055,0.023
21,Native Hawaiian and Other Pacific Islander alone,Totals,0.375,0.122,0.114,0.099,0.073,0.064,0.068,0.027,0.055
22,Native Hawaiian and Other Pacific Islander alone,Non Hispanic,0.358,0.121,0.117,0.101,0.079,0.058,0.076,0.031,0.059
24,Native Hawaiian and Other Pacific Islander alone,Hispanic,0.451,0.126,0.102,0.093,0.049,0.089,0.041,0.012,0.041
25,Two or more races,Totals,0.503,0.113,0.095,0.076,0.058,0.037,0.063,0.027,0.029
26,Two or more races,Non Hispanic,0.501,0.114,0.095,0.077,0.058,0.034,0.059,0.030,0.031
28,Two or more races,Hispanic,0.512,0.109,0.096,0.069,0.057,0.044,0.073,0.018,0.023

In [131]:
pcts_filtered = pcts[(pcts['Hispanic origin'] == 'Non Hispanic') | (pcts['Race'] == 'Totals')]

pcts_filtered

,Race,Hispanic origin,No Income pct,"Less than $10,000 pct","$10,000 to $20,000 pct","$20,000 to $30,000 pct","$30,000 to $40,000 pct","$40,000 to $50,000 pct","$50,000 to $75,000 pct","$75,000 to $100,000 pct","$100,000 and over pct"
0,Totals,Totals,0.287,0.118,0.123,0.101,0.084,0.065,0.102,0.049,0.070
1,Totals,Non Hispanic,0.258,0.120,0.123,0.100,0.085,0.068,0.110,0.055,0.080
3,Totals,Hispanic,0.417,0.110,0.122,0.104,0.082,0.051,0.065,0.024,0.026
6,White alone,Non Hispanic,0.228,0.118,0.123,0.102,0.087,0.073,0.119,0.060,0.089
10,Black or African American alone,Non Hispanic,0.338,0.128,0.138,0.103,0.086,0.058,0.085,0.032,0.031
14,American Indian and Alaska Native alone,Non Hispanic,0.344,0.159,0.133,0.102,0.068,0.062,0.077,0.023,0.034
18,Asian alone,Non Hispanic,0.306,0.124,0.096,0.078,0.071,0.053,0.099,0.062,0.111
22,Native Hawaiian and Other Pacific Islander alone,Non Hispanic,0.358,0.121,0.117,0.101,0.079,0.058,0.076,0.031,0.059
26,Two or more races,Non Hispanic,0.501,0.114,0.095,0.077,0.058,0.034,0.059,0.030,0.031

In [132]:
pcts_filtered.sum(axis=1)

0    1.000
1    1.000
3    1.000
6    1.000
10   1.000
14   1.001
18   1.000
22   0.999
26   1.000
dtype: float64

In [133]:
totals_filtered = df[(pcts['Hispanic origin'] == 'Non Hispanic') | (pcts['Race'] == 'Totals')]['Totals']

pd.set_option('display.float_format', lambda x: '%.3f' % x)

totals_filtered-pcts_filtered.sum(axis=1)*totals_filtered

0     2.000
1     4.000
3     0.000
6    -4.000
10    1.000
14   -3.000
18    0.000
22    1.000
26    1.000
dtype: float64

In [134]:
pcts_filtered.to_csv('assets/cpsincomebyraceandhispanicorigin.csv')